#!/usr/bin/env bash
# Change DNS resolution for specific hosts

sudo sed -i '/localhost/d' /etc/hosts
sudo sed -i '/facebook.com/d' /etc/hosts

echo "127.0.0.2    localhost" | sudo tee -a /etc/hosts
echo "8.8.8.8      facebook.com" | sudo tee -a /etc/hosts
